### ISSUE TITLE
Fail to read the score output

### ISSUE THREAD

**Issue by vuongvantinh** [PikaCat-OuO/Pikafish#5]
Thank you for your amazing work.

This engine is much more powerful than other ones in my test. There is only a problem that the score is not displayed (this value is always displayed as 0), whereas other engines can display this value correctly. I am not sure where this problem come from (from my Intella GUI or from the pikafish).

I also found the same issue with fairy-stockfish as be mentioned in [this post.](https://github.com/ianfab/Fairy-Stockfish/issues/413)

**Comment by Vincentzyx** [comment]
Thank you for your appreciation! The GUI you are using is too old and doesn't support "score cp" output by engine, which is the standard UCI protocol. Please consider using other newer GUIs like BH3.6, link below.
https://www.chessdb.cn/bh/bhsim.zip

**Comment by vuongvantinh** [comment]
Thank you for the quick response.

Do you know other GUIs with english version? I am not familiar with Chinese.
I found Ethinker from [this site](http://www.xqpt.com/) has the English version and support "score cp" output but it displays the raw score (not multiply by 100). Do you know how to config to display the score with 100 x value?

I also found that Pikafish often overestimates the score on the first moves (80-110), whereas isfairy-stockfish and other engines often return a value in range 20-50. Does this come from the nnue weight of pikafish or is there something wrong with my engine configuration?

![image](https://user-images.githubusercontent.com/42363044/192332138-f8565493-6b88-4eb8-9759-d667b75a92b0.png)

**Comment by PikaCat-OuO** [comment]
> Do you know of any other GUIs that have an English version? I'm not fluent in Chinese.
I found the Ethinker engine from [this site](http://xqpt.com/) has the English version and support "score cp" output, however it currently only displays the raw score (not multiply by 100). Do you know how to set up the score to be displayed with a 100x value?

Well, feel free to use the free version of PengfeiChess GUI, it has English and display score 100x value. It can be downloaded in this link below:
`https://filehelper.stkme.com/FileDownload/GetContent?path=current%2FPengfeiChess.zip&guid=5c8a46f9f29f4813bbd1d6b4eee7e8fa&code=1525`

> Additionally, I've observed that Pikafish regularly overestimates the score on the first moves (give a score of 80–110), whereas other engines frequently give a score in the range of 20–50. Is there a problem with my engine configuration, or is this the result of the trained weight of nnue in pikafish?

This is this the result of the trained weight of nnue in pikafish. We are trying to fix that recently.
