### ISSUE TITLE
Author, your website has a vulnerability, unable to display the latest NN

### ISSUE THREAD

**Issue by jeffnier1989** [PikaCat-OuO/Pikafish#6]
http://pikafish.org/

**Comment by PikaCat-OuO** [comment]
Sorry for causing any inconvenience. The website is still under construction. The maintainer of the website @Vincentzyx  is very busy these days. It will be fine in the future. For now, you can find the latest NN in the `release` of this repo https://github.com/PikaCat-OuO/Pikafish/releases/tag/Pikafish-2022-09-19

**Comment by jeffnier1989** [comment]
> 很抱歉造成任何不便。该网站仍在建设中。网站的维护者@Vincentzyx 这几天很忙。将来会好的。`release`现在，你可以在这个 repo中找到最新的 NN https://github.com/PikaCat-OuO/Pikafish/releases/tag/Pikafish-2022-09-19
OK I show understanding
